apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    app: sw-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sw-lbl
  template:
    metadata:
      labels:
        app: sw-lbl
    spec:
      containers:
      - name: simple-web
        image: falakidocker/simple-web-image:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
spec:
  selector:
    app: sw-lbl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sw-ingress
spec:
  rules:
  - host: simple-web.com
    http:
      paths:
      - backend: 
          serviceName: simple-web-service
          servicePort: 80

